### ISSUE TITLE
Peer-to-Peer code review

### ISSUE THREAD

**Issue by why-a-en** [tsheporamantso/Portfolio-Bootstrap#2]
Great job on trying to replicate the Figma design as much as possible. However, a few changes are required.

- I suggest using the bootstrap class 'navbar-brand'
- Instead of inline CSS styling, kindly use these bootstrap classes in your hamburger list ( the bootstrap classes we are suggesting to use are w for width, h for height, m for margin, and bg-color for background-color)
- Instead of using the img tag, I suggest you use it as a background-image in your external CSS file and please reposition it appropriately

**Comment by tsheporamantso** [comment]
Thank you for the recommendations:-
- [ ] I have used Bootstrap `navbar-brand` class as suggested for my navigation bar.
- [ ]  Used Bootstrap `w` for width, `h` for height, `m` for marging and `bg-color-primary` to style the hamburger list
